#! /bin/sh
### BEGIN INIT INFO
# Provides:          grr_http_server
# Required-Start:    $network $named $local_fs $syslog
# Required-Stop:     $network $named $local_fs $syslog
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       GRR Rapid Response HTTP server
### END INIT INFO

DESC="GRR Rapid Response HTTP server"
NAME="grr-http-server"
DAEMON_ARGS="--start_http_server"

CWD=$(dirname "$0")

# Call the common script.
. "${CWD}/grr-server"
