
all:
	epydoc -o . --html  -n "Rekall Memory Forensics"  \
	--show-sourcecode -u http://www.rekall-forensic.com/  \
	--inheritance=included --no-private --css epydoc_rekall.css \
	--graph=classtree --graph-font-size=8 --debug \
	`find ~/rekall/rekall -name \*.py`