.Dd Nov 13, 2012
.Dt grrd
.Sh NAME
.Nm grrd
.Nd GRR Rapid Response Client
.Sh DESCRIPTION
.Nm grrd
is a Rapid Response Client
.Sh BUGS
Please report bugs of any kind to <grr-dev@googlegroups.com> or on the project website:
https://github.com/google/grr
.Sh COPYRIGHT
Copyright 2011 Google Inc.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
