{
 "title": "Workers Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Active Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{job=\"grr_worker\"})",
     "legendFormat": "Number of Active Worker Processes"
    }
   ]
  },
  {
   "title": "Outstanding Tasks vs. Number of Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(threadpool_outstanding_tasks{job=\"grr_worker\"})",
     "legendFormat": "Outstanding Tasks"
    },
    {
     "expr": "sum(threadpool_threads{job=\"grr_worker\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Threadpool Latency vs. Queuing Time Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(threadpool_working_time_sum{job=\"grr_worker\"}[5m])) /\nsum(rate(threadpool_working_time_count{job=\"grr_worker\"}[5m]))",
     "legendFormat": "Latency"
    },
    {
     "expr": "sum(rate(threadpool_queueing_time_sum{job=\"grr_worker\"}[5m])) /\nsum(rate(threadpool_queueing_time_count{job=\"grr_worker\"}[5m]))",
     "legendFormat": "Queueing Time"
    }
   ]
  },
  {
   "title": "Successful Flows vs. Failed Flows Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_completions_total{job=\"grr_worker\"}[5m]))",
     "legendFormat": "Successes"
    },
    {
     "expr": "sum(rate(flow_errors_total{job=\"grr_worker\"}[5m]))",
     "legendFormat": "Failures"
    }
   ]
  }
 ]
}