{
 "title": "Frontend Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Active Frontend Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{job=\"grr_frontend\"})"
    }
   ]
  },
  {
   "title": "Frontend QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(frontend_request_count_total{job=\"grr_frontend\"}[1m])",
     "legendFormat": "Requests - {{instance}}"
    }
   ]
  },
  {
   "title": "Frontend Active Tasks Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "frontend_active_count", "legendFormat": "Active Tasks - {{instance}}" }
   ]
  },
  {
   "title": "Frontend Request Latency Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(frontend_request_latency_sum{job=\"grr_frontend\"}[5m]) /\nrate(frontend_request_latency_count{job=\"grr_frontend\"}[5m])",
     "legendFormat": "Latency - {{instance}} "
    }
   ]
  }
 ]
}