Database.implementation: MysqlDB
Blobstore.implementation: DbBlobStore

Mysql.host: 127.0.0.1
Mysql.port: 3306
Mysql.database_name: grr
Mysql.database: grr
Mysql.database_username: grr
Mysql.username: grr
Mysql.database_password: grr
Mysql.password: grr

Client.server_urls:
- http://localhost:8080/

AdminUI.url: http://localhost:8000
AdminUI.bind: 0.0.0.0
AdminUI.headless: false
AdminUI.webauth_manager: BasicWebAuthManager
AdminUI.use_precompiled_js: True
AdminUI.csrf_secret_key: O$YTx01F2BuxgT4DoVSI hJVuhWOxyuuxJhg#lg96ARF_fWLabzN5kjAy0UBcI9GDrUPo1v
  b7PyF3vj4pqRrc8oegeJ8XgIyI5X

API.DefaultRouter: ApiCallRouterWithoutChecks

Logging.domain: localhost
Logging.verbose: true
Logging.engines: file
Logging.path: /grr
Logging.filename: /grr/grr-server.log

Monitoring.alert_email: grr-monitoring@localhost
Monitoring.emergency_access_email: grr-emergency@localhost

Client.fleetspeak_enabled: true

ClientBuilder.fleetspeak_bundled: true

FleetspeakFrontend Context:
  Server.fleetspeak_message_listen_address: 0.0.0.0:11111

Server.fleetspeak_enabled: true
Server.fleetspeak_server: localhost:4444
Server.initialized: true
