#!/usr/bin/env python
"""A mapping of export converters name and implementation."""

from grr_response_server import export_converters_registry
from grr_response_server.export_converters import auto_export_converters
from grr_response_server.export_converters import buffer_reference
from grr_response_server.export_converters import client_snapshot
from grr_response_server.export_converters import cron_tab_file
from grr_response_server.export_converters import dict as dict_converter
from grr_response_server.export_converters import execute_response
from grr_response_server.export_converters import file
from grr_response_server.export_converters import launchd_plist
from grr_response_server.export_converters import log_message
from grr_response_server.export_converters import memory
from grr_response_server.export_converters import network
from grr_response_server.export_converters import osquery
from grr_response_server.export_converters import process
from grr_response_server.export_converters import proto_wrappers
from grr_response_server.export_converters import software_package


# TODO - Test that this function contains all inheritors.
def RegisterExportConverters():
  """Registers all ExportConverters."""
  export_converters_registry.RegisterProto(
      buffer_reference.BufferReferenceToExportedMatchConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      client_snapshot.ClientSnapshotToExportedClientConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      cron_tab_file.CronTabFileToExportedCronTabEntryProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      dict_converter.DictToExportedDictItemsConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      execute_response.ExecuteResponseConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(file.FileFinderResultConverterProto)  # pyrefly: ignore[bad-argument-type]
  export_converters_registry.RegisterProto(
      file.StatEntryToExportedFileConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      file.StatEntryToExportedRegistryKeyConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      file.CollectMultipleFilesResultToExportedFileConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      file.CollectFilesByKnownPathResultToExportedFileConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      launchd_plist.LaunchdPlistConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      log_message.LogMessageToExportedStringConverter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      memory.ProcessMemoryErrorConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      memory.YaraProcessScanMatchConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      network.DNSClientConfigurationToExportedDNSClientConfigurationProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      network.InterfaceToExportedNetworkInterfaceConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      osquery.OsqueryTableExportConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      osquery.OsqueryResultExportConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      process.ProcessToExportedNetworkConnectionConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      process.ProcessToExportedProcessConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      proto_wrappers.BytesValueToExportedBytesConverter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      proto_wrappers.StringValueToExportedStringConverter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      software_package.SoftwarePackageConverterProto  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      software_package.SoftwarePackagesConverterProto  # pyrefly: ignore[bad-argument-type]
  )


def RegisterAutoGeneratedExportConverters():
  """Registers all auto-generated ExportConverters."""
  export_converters_registry.RegisterProto(
      auto_export_converters.BytesValueToAutoGeneratedExportedBytesValue1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.CollectBrowserHistoryResultToAutoGeneratedExportedCollectBrowserHistoryResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.CollectCloudVMMetadataResultToAutoGeneratedExportedCollectCloudVMMetadataResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.CollectDistroInfoResultToAutoGeneratedExportedCollectDistroInfoResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.CollectLargeFileFlowResultToAutoGeneratedExportedCollectLargeFileFlowResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.DummyFlowResultToAutoGeneratedExportedDummyFlowResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.ExecuteBinaryResponseToAutoGeneratedExportedExecuteBinaryResponse1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.ExecutePythonHackResultToAutoGeneratedExportedExecutePythonHackResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.GetCrowdstrikeAgentIdResultToAutoGeneratedExportedGetCrowdstrikeAgentIdResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.GetMemorySizeResultToAutoGeneratedExportedGetMemorySizeResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.HardwareInfoToAutoGeneratedExportedHardwareInfo1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.KnowledgeBaseToAutoGeneratedExportedKnowledgeBase1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.LaunchExecutableResultToAutoGeneratedExportedLaunchExecutableResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.ListContainersFlowResultToAutoGeneratedExportedListContainersFlowResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.ListNamedPipesFlowResultToAutoGeneratedExportedListNamedPipesFlowResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.NetworkConnectionToAutoGeneratedExportedNetworkConnection1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.OSXServiceInformationToAutoGeneratedExportedOSXServiceInformation1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.TimelineResultToAutoGeneratedExportedTimelineResult1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.YaraProcessDumpResponseToAutoGeneratedExportedYaraProcessDumpResponse1Converter  # pyrefly: ignore[bad-argument-type]
  )
  export_converters_registry.RegisterProto(
      auto_export_converters.YaraProcessScanMissToAutoGeneratedExportedYaraProcessScanMiss1Converter  # pyrefly: ignore[bad-argument-type]
  )
