#! /bin/sh
### BEGIN INIT INFO
# Provides:          grr_worker
# Required-Start:    $network $named $local_fs $syslog
# Required-Stop:     $network $named $local_fs $syslog
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       GRR Rapid Response worker
### END INIT INFO

DESC="GRR Rapid Response worker"
NAME="grr-worker"
DAEMON_ARGS="--start_worker"

CWD=$(dirname "$0")

# Call the common script.
. "${CWD}/grr-server"
