#! /bin/sh
### BEGIN INIT INFO
# Provides:          grr_ui
# Required-Start:    $network $named $local_fs $syslog
# Required-Stop:     $network $named $local_fs $syslog
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       GRR Rapid Response user interface
### END INIT INFO

DESC="GRR Rapid Response user interface"
NAME="grr-ui"
DAEMON_ARGS="--start_ui"

CWD=$(dirname "$0")

# Call the common script.
. "${CWD}/grr-server"
