check_id: CIS-INETD-WITH-NO-SERVICES
# CIS check 4.01
method:
  - target: {os:['Linux']}
    hint:
      problem: xinetd running with no xinetd-managed services.
      fix: |
        Disable xinetd as the service is not required.
        (ref) CIS Debian Benchmark v1.0-4.1
    match: ALL
    probe:
      - artifact: 'LinuxServices'
        filters:
          - type: 'ObjectFilter'
            expression: name is "xinetd" and starts is 1
      - artifact: 'LinuxServices'
        match: NONE
        filters:
          - type: 'ObjectFilter'
            expression: start_mode is "XINETD"
---
check_id: CIS-SERVICE-LEGACY-SERVICE-ENABLED
# CIS checks 3.01, 3.03, 3.04, 3.05, 3.06, 3.09
method:
  - target: {os:['Linux']}
    hint:
      problem: Legacy services are running.
      fix: |
        This system has legacy services enabled that are insecure and should
        not be running. In some cases, there may be more suitable replacements
        for these services.

        If a similar service is needed, use a secure replacement.  Otherwise,
        services should simply be disabled.

        (ref) CIS Debian Benchmark v1.0-3.* and 1.0-4.*
      format: "{name} is started by {start_mode}"
    probe:
      - artifact: 'LinuxServices'
        baseline:
          - type: 'ObjectFilter'
            expression: starts is 1
        mode: PARALLEL
        filters:
          - type: 'ObjectFilter'
            expression: name contains "chargen"
          - type: 'ObjectFilter'
            expression: name contains "discard"
          - type: 'ObjectFilter'
            expression: name contains "echo"
          - type: 'ObjectFilter'
            expression: name contains "fingerd"
          - type: 'ObjectFilter'
            expression: name contains "ftpd"
          - type: 'ObjectFilter'
            expression: name contains "telnet"
          - type: 'ObjectFilter'
            expression: name contains "whois"
          - type: 'ObjectFilter'
            expression: name contains "xfont-server"
          - type: 'ObjectFilter'
            expression: |
              name inset ["telnet", "ntalkd", "lpd", "lpdng", "rcp", "rlogin",
                          "rsh", "ident","nis","ypserv"]
---
check_id: CIS-SERVICE-SHOULD-NOT-RUN
# CIS check 4.14
method:
  - target: {os:['Linux']}
    hint:
      problem: Remote administration services are running.
      fix: |
        Disable services that provide remote administration facilities.

        If services must run, ensure that access to them is:
          - restricted to trusted hosts and networks.
          - strongly authenticated.
          - only accessible over an encrypted connection.

        (ref) CIS Debian Benchmark v1.0-3.* and 1.0-4.*
      format: "{name} is started by {start_mode}"
    probe:
      - artifact: 'LinuxServices'
        baseline:
          - type: 'ObjectFilter'
            expression: starts is 1
        filters:
          - type: 'ObjectFilter'
            expression: |
              name inset ["snmp","webmin"]
---
check_id: CIS-SERVICE-SHOULD-RUN
# CIS check 3.02
method:
  - target: {os:['Linux']}
    hint:
      problem: Recommended services are not started at boot time.
      fix: |
        Configure these services to start by default.

        (ref) CIS Debian Benchmark v1.0-2.4 and 1.0-3.2
    probe:
      - artifact: 'LinuxServices'
        hint:
          problem: Sysstat is not started at boot time.
        match: NONE
        filters:
          - type: 'ObjectFilter'
            expression: 'name is "sysstat" and start is 1'
      - artifact: 'LinuxServices'
        hint:
          problem: A firewall is not started at boot time.
        match: NONE
        filters:
          - type: 'ObjectFilter'
            expression: 'name inset ["iptables", "ufw"] and start is 1'
---
check_id: CIS-SERVICE-SHOULD-NOT-LISTEN
method:
  - target: {os:['Linux']}
    hint:
      problem: Insecure services are accessible over the network.
      fix: |
        Either disable these services or configure them to only allow
        access via the loopback address.

        (ref) CIS Debian Benchmark v1.0-3.* and 1.0-4.*
      format: "{name} (pid {pid}) listens on {connections.local_address.ip}"
    match: ALL
    probe:
      - artifact: 'ListProcessesGrr'
        result_context: 'RAW'
        baseline:
          - type: 'ObjectFilter'
            expression: |
              @connections (
                      state is "LISTEN"
                      AND
                      (
                        (
                          family is "INET" and
                          local_address.ip isnot "127.0.0.1"
                        )
                        OR
                        (
                          family is "INET6" and
                          local_address.ip isnot "::1"
                        )
                      )
              )
        filters:
          - type: 'ObjectFilter'
            expression: 'name inset ["x11","xorg"]'
---
check_id: CIS-SERVICE-LOGSERVER-RUNNING
method:
  - target: {os:['Linux']}
    hint:
      problem: Logging software is not running.
      fix: "Configure a logserver to run at boot time."
    match: 'NONE'
    probe:
      - artifact: 'ListProcessesGrr'
        result_context: 'RAW'
        filters:
          - type: 'ObjectFilter'
            expression: name inset ["rsyslogd", "syslog", "syslog-ng"]
