#!/usr/bin/env python
"""This file imports the Python std lib so it can be used by components."""

# pylint: disable=g-import-not-at-top, unused-import, using-constant-test

if False:
  import BaseHTTPServer
  import CGIHTTPServer
  import ConfigParser
  import Cookie
  import DocXMLRPCServer
  import HTMLParser
  import MimeWriter
  import Queue
  import SimpleHTTPServer
  import SimpleXMLRPCServer
  import SocketServer
  import StringIO
  import UserDict
  import UserList
  import UserString
  import _LWPCookieJar
  import _abcoll
  import _osx_support
  import _pyio
  import _strptime
  import _sysconfigdata
  import _threading_local
  import _weakrefset
  import abc
  import aifc
  import anydbm
  import argparse
  import ast
  import asynchat
  import asyncore
  import atexit
  import audiodev
  import base64
  import bdb
  import binhex
  import bisect
  import bsddb.db
  import bsddb.dbobj
  import bsddb.dbrecio
  import bsddb.dbshelve
  import bsddb.dbtables
  import bsddb.dbutils
  import cProfile
  import calendar
  import cgi
  import cgitb
  import chunk
  import cmd
  import code
  import codecs
  import codeop
  import collections
  import colorsys
  import commands
  import compileall
  import compiler.ast
  import compiler.consts
  import compiler.future
  import compiler.misc
  import compiler.pyassem
  import compiler.pycodegen
  import compiler.symbols
  import compiler.syntax
  import compiler.transformer
  import compiler.visitor
  import contextlib
  import cookielib
  import copy
  import copy_reg
  import csv
  import ctypes._endian
  import ctypes.util
  import curses.ascii
  import curses.has_key
  import curses.panel
  import curses.textpad
  import curses.wrapper
  import dbhash
  import decimal
  import difflib
  import dircache
  import dis
  import distutils.archive_util
  import distutils.bcppcompiler
  import distutils.ccompiler
  import distutils.cmd
  import distutils.command.bdist
  import distutils.command.bdist_dumb
  import distutils.command.bdist_rpm
  import distutils.command.bdist_wininst
  import distutils.command.build
  import distutils.command.build_clib
  import distutils.command.build_ext
  import distutils.command.build_py
  import distutils.command.build_scripts
  import distutils.command.check
  import distutils.command.clean
  import distutils.command.config
  import distutils.command.install
  import distutils.command.install_data
  import distutils.command.install_egg_info
  import distutils.command.install_headers
  import distutils.command.install_lib
  import distutils.command.install_scripts
  import distutils.command.register
  import distutils.command.sdist
  import distutils.command.upload
  import distutils.config
  import distutils.core
  import distutils.cygwinccompiler
  import distutils.debug
  import distutils.dep_util
  import distutils.dir_util
  import distutils.dist
  import distutils.emxccompiler
  import distutils.errors
  import distutils.extension
  import distutils.fancy_getopt
  import distutils.file_util
  import distutils.filelist
  import distutils.log
  import distutils.spawn
  import distutils.sysconfig
  import distutils.text_file
  import distutils.unixccompiler
  import distutils.util
  import distutils.version
  import distutils.versionpredicate
  import doctest
  import dumbdbm
  import dummy_thread
  import dummy_threading
  import email._parseaddr
  import email.base64mime
  import email.charset
  import email.encoders
  import email.errors
  import email.feedparser
  import email.generator
  import email.header
  import email.iterators
  import email.message
  import email.mime.application
  import email.mime.audio
  import email.mime.base
  import email.mime.image
  import email.mime.message
  import email.mime.multipart
  import email.mime.nonmultipart
  import email.mime.text
  import email.parser
  import email.quoprimime
  import email.utils
  import filecmp
  import fileinput
  import fnmatch
  import formatter
  import fpformat
  import fractions
  import ftplib
  import functools
  import genericpath
  import getopt
  import getpass
  import gettext
  import glob
  import gzip
  import hashlib
  import heapq
  import hmac
  import hotshot.log
  import hotshot.stats
  import hotshot.stones
  import htmlentitydefs
  import htmllib
  import httplib
  import ihooks
  import imaplib
  import imghdr
  import imputil
  import inspect
  import io
  import json.decoder
  import json.encoder
  import json.scanner
  import json.tool
  import keyword
  import linecache
  import locale
  import logging.config
  import logging.handlers
  import macpath
  import macurl2path
  import mailbox
  import mailcap
  import markupbase
  import md5
  import mhlib
  import mimetools
  import mimetypes
  import mimify
  import modulefinder
  import multifile
  import multiprocessing.connection
  import multiprocessing.dummy.connection
  import multiprocessing.forking
  import multiprocessing.heap
  import multiprocessing.managers
  import multiprocessing.pool
  import multiprocessing.process
  import multiprocessing.queues
  import multiprocessing.reduction
  import multiprocessing.sharedctypes
  import multiprocessing.synchronize
  import multiprocessing.util
  import mutex
  import netrc
  import new
  import nntplib
  import ntpath
  import nturl2path
  import numbers
  import opcode
  import optparse
  import os
  import os2emxpath
  import pdb
  import pickle
  import pickletools
  import pipes
  import pkgutil
  import platform
  import plistlib
  import popen2
  import poplib
  import posixfile
  import posixpath
  import pprint
  import profile
  import pstats
  import pty
  import py_compile
  import pyclbr
  import pydoc
  import pydoc_data.topics
  import quopri
  import random
  import re
  import rfc822
  import rlcompleter
  import robotparser
  import runpy
  import sched
  import sets
  import sgmllib
  import sha
  import shelve
  import shlex
  import shutil
  import site
  import smtpd
  import smtplib
  import sndhdr
  import socket
  import sqlite3.dbapi2
  import sqlite3.dump
  import sre
  import sre_compile
  import sre_constants
  import sre_parse
  import ssl
  import stat
  import statvfs
  import string
  import stringold
  import stringprep
  import struct
  import subprocess
  import sunau
  import sunaudio
  import symbol
  import symtable
  import sysconfig
  import tabnanny
  import tarfile
  import telnetlib
  import tempfile
  import test.pystone
  import test.regrtest
  import test.test_support
  import textwrap
  import this
  import threading
  import timeit
  import toaiff
  import token
  import tokenize
  import trace
  import traceback
  import tty
  import types
  import urllib
  import urllib2
  import urlparse
  import user
  import uu
  import uuid
  import warnings
  import wave
  import weakref
  import whichdb
  import wsgiref.handlers
  import wsgiref.headers
  import wsgiref.simple_server
  import wsgiref.util
  import wsgiref.validate
  import xdrlib
  import xml.dom.NodeFilter
  import xml.dom.domreg
  import xml.dom.expatbuilder
  import xml.dom.minicompat
  import xml.dom.minidom
  import xml.dom.pulldom
  import xml.dom.xmlbuilder
  import xml.etree.ElementInclude
  import xml.etree.ElementPath
  import xml.etree.ElementTree
  import xml.etree.cElementTree
  import xml.parsers.expat
  import xml.sax._exceptions
  import xml.sax.expatreader
  import xml.sax.handler
  import xml.sax.saxutils
  import xml.sax.xmlreader
  import xmllib
  import xmlrpclib
  import zipfile

  # lib-dynload
  import audioop
  import _bsddb
  import bz2
  import _codecs_cn
  import _codecs_hk
  import _codecs_iso2022
  import _codecs_jp
  import _codecs_kr
  import _codecs_tw
  import crypt
  import _csv
  import _ctypes_test
  import _ctypes
  import _curses_panel
  import _curses
  import datetime
  import dbm
  import _elementtree
  import fpectl
  import future_builtins
  import gdbm
  import _hashlib
  import _hotshot
  import _json
  import linuxaudiodev
  import _lsprof
  import mmap
  import _multibytecodec
  import _multiprocessing
  import nis
  import ossaudiodev
  import parser
  import pyexpat
  import readline
  import resource
  import _sqlite3
  import _ssl
  import termios
  import _testcapi
  import _tkinter
