# Configuration file artifacts.
name: SshdConfigFile
doc: Sshd configuration
collectors:
- collector_type: FILE
  args:
    path_list:
      - '/etc/ssh/sshd_config'
labels: [Configuration Files]
supported_os: [Linux]
---
name: SshdConfigCmd
doc: Output of sshd -T.
collectors:
- collector_type: COMMAND
  args:
    args: [-T]
    cmd: /usr/sbin/sshd
labels: [Configuration Files]
supported_os: [Linux]
